"""Safe cleanup of artifacts generated by the research workflow."""

from __future__ import annotations

from dataclasses import dataclass
import os
from pathlib import Path
import shutil


@dataclass(frozen=True, slots=True)
class CleanupResult:
    """Summary of files and directories removed from the output root."""

    output_root: Path
    removed: tuple[str, ...]

    @property
    def removed_count(self) -> int:
        return len(self.removed)


def clean_outputs(
    output_root: str | Path,
    *,
    expected_root: str | Path,
) -> CleanupResult:
    """Remove only children of the explicitly expected workflow output root."""

    root = Path(output_root).resolve()
    expected = Path(expected_root).resolve()
    if root != expected or root.name != "outputs":
        raise ValueError(
            "Limpieza rechazada: la ruta debe ser exactamente "
            "ResearchWorkflow/outputs."
        )
    if root.exists() and not root.is_dir():
        raise ValueError(f"La ruta de outputs no es una carpeta: {root}")

    removed: list[str] = []
    if root.exists():
        for child in root.iterdir():
            if child.name == "README.md":
                continue
            if child.parent.resolve() != root:
                raise ValueError(f"Elemento fuera de la ruta autorizada: {child}")
            removed.append(child.name)
            is_junction = getattr(child, "is_junction", lambda: False)()
            if child.is_symlink():
                child.unlink()
            elif is_junction:
                os.rmdir(child)
            elif child.is_dir():
                shutil.rmtree(child)
            else:
                child.unlink()

    root.mkdir(parents=True, exist_ok=True)
    return CleanupResult(root, tuple(sorted(removed)))
